Fix compilation
Tested this out as per the documentation here - https://formatjs.io/docs/getting-started/message-distribution - but every time I ran the command I got

```
Error: Cannot find module './lang/en.json'
Require stack:
- /Users/adamjenkins/Documents/GitHub/web-client/node_modules/@formatjs/cli/src/compile.js
- /Users/adamjenkins/Documents/GitHub/web-client/node_modules/@formatjs/cli/src/cli.js
- /Users/adamjenkins/Documents/GitHub/web-client/node_modules/@formatjs/cli/bin/formatjs
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.compile [as default] (/Users/adamjenkins/Documents/GitHub/web-client/node_modules/@formatjs/cli/src/compile.js:7:20)
    at Command.<anonymous> (/Users/adamjenkins/Documents/GitHub/web-client/node_modules/@formatjs/cli/src/cli.js:156:41)
    at Command.listener [as _actionHandler] (/Users/adamjenkins/Documents/GitHub/web-client/node_modules/@formatjs/cli/node_modules/commander/index.js:413:31)
    at Command._parseCommand (/Users/adamjenkins/Documents/GitHub/web-client/node_modules/@formatjs/cli/node_modules/commander/index.js:914:14)
    at Command._dispatchSubcommand (/Users/adamjenkins/Documents/GitHub/web-client/node_modules/@formatjs/cli/node_modules/commander/index.js:865:18)
    at Command._parseCommand (/Users/adamjenkins/Documents/GitHub/web-client/node_modules/@formatjs/cli/node_modules/commander/index.js:882:12)
adamjenkins@MacBook-Pro web-client % npx formatjs compile ./lang/en.json --out-file compiled-lang/en.json
```

When I changed it to use readJSONSync (because the cli already uses fs-extra so why not) it worked like a charm. I didn't see a bug report, is anybody else experiencing this issue?